codeforboston/codeforboston.org

LICENSE, _pages/new-member.html
Sorry I can't make it tonight, but figured I could start contributing code anytime...
=> Add a license and handy links

_data/projects/ongoing.yml, _pages/projects.html
- added past/current project buttons in _pages/projects
- added list of current projects as _data/ongoing.yml
- slightly modified text in project submission section
=> added past/current project buttons to projects page

_data/projects/ongoing.yml, _data/resources/tools.yml, _data/team.yml, _pages/projects.html, _pages/tools.html
- fixed tools page
(note: may need to be rebased following update-projects-page and update-core-team merges)
=> Update tools page

_data/projects/ongoing.yml, _data/team.yml, _pages/projects.html
- added names/emails for new core team members
(note: may need to be rebased following update-projects-page merge)
=> Update core team

_data/projects/active.yml
Please let us know if there are any issues  @mzagaja
=> Teaser trailer for 12/19/17

_data/projects/active.yml
=> Update active.yml video added

_data/projects/active.yml
new link -->> Dropbox link! <<-- new video for interactive Doc
=> new video for iDoc

_data/projects/active.yml
Updated link to more recent link.
=> Changed "Interactive Film Documentary" Video Link.

_data/events/active.yml
=> Added Public Interest Potluck

_data/projects/active.yml
User testing with PH case managers next week. Need designers!
=> Updates to cliff effects.

_data/projects/active.yml
new (shorter!) promo video for feb
also some new settings so the video plays larger and hopefully not letter-boxed
=> new idoc promo

_data/projects/active.yml
=> Update cliff effects

_data/projects/active.yml
Added MVP language to interactive documentary
=> Added MVP language to interactive documentary

hacknight.html
In order,
* Removes border from the CfB logo. Inline styles aren't the prettiest but it'll withstand reveal.js theme changes
* Fixes that one ordered list that rendered as a code block, wow reveal.js is sensitive
* Gets around the awkward linebreaking thing by rendering events as a list
=> fix minor hacknight template things

_data/projects/active.yml
I'm not sure if it's formatted correctly.
=> Michelle proposed a change to Cliff Effects

css/main.scss
Increased spacing between paragraphs in main.scss file in .cfbgrid
=> Increased spacing between paragraphs in main.scss file

readme.md
=> Updating readme to include new ruby dependency

css/main.scss, index.html
* Update front page copy to reflect ongoing nature of virtual hack nights.
* Modify links and buttons to more compactly fit on the page.
* Reformat using Prettier
=> Update Front Page

_data/projects/active.yml
Also testing out the Netlify deploy preview, which should be the last "Details" link in the checks/tests.
=> Link windfall awareness project

ndoch.html
=> Corrects styling for all <h> elements

ndoch.html
Added CFA event's and updated some descriptions
=> Updated more event and descriptions

_data/projects/inactive.yml, index.html
Update front page message to show in person
Update the link for one of the archived projects to go to the repo.
=> update_front_page with in person info and fix link on subpage

_data/projects/active.yml
Please let me know if any information is missing. Thanks!
=> Add Urban League Heat Pump Accelerator information in active projects

_data/projects/active.yml
=> Add Police Data trust repository link
